# Codecov configuration
# This file configures how Codecov processes and reports coverage

coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - 'src/examples/**/*'
  - 'test/**/*'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.config.*'
  - '**/*.d.ts'
